"""empty message

Revision ID: 1714727058ea
Revises: 206d6bdd3243
Create Date: 2024-07-02 01:39:29.176247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1714727058ea'
down_revision: Union[str, None] = '206d6bdd3243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lud_session_log', sa.Column('amount_cash', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lud_session_log', 'amount_cash')
    # ### end Alembic commands ###
