"""empty message

Revision ID: 742fb8d6645d
Revises: 9f4a23f9d8e9
Create Date: 2024-07-04 19:37:50.610061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742fb8d6645d'
down_revision: Union[str, None] = '9f4a23f9d8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lud_sessions', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lud_sessions', 'chat_id')
    # ### end Alembic commands ###
