"""empty message

Revision ID: 9f4a23f9d8e9
Revises: 1714727058ea
Create Date: 2024-07-02 18:45:01.569508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4a23f9d8e9'
down_revision: Union[str, None] = '1714727058ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('lud_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'lud_sessions', ['lud_session_id'], ['id'])
    op.alter_column('users', 'statistics_viewing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'statistics_viewing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'lud_session_id')
    # ### end Alembic commands ###
